version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dotNETproj
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: